# Name your project! Project names should contain only lowercase characters
# and underscores. A good package name should reflect your organization's
# name or the intended use of these models
name: 'thelook_analytics'
version: '1.0.0'
config-version: 2

# This setting configures which "profile" dbt uses for this project.
profile: 'thelook_analytics'

# These configurations specify where dbt should look for different types of files.
model-paths: ["models"]
analysis-paths: ["analyses"]
test-paths: ["tests"]
seed-paths: ["seeds"]
macro-paths: ["macros"]
snapshot-paths: ["snapshots"]

target-path: "target"  # directory which will store compiled SQL files
clean-targets:         # directories to be removed by `dbt clean`
  - "target"
  - "dbt_packages"

# Configuring models
# Full documentation: https://docs.getdbt.com/reference/model-configurations

models:
  thelook_analytics:
    # Staging models - temporary views for data cleaning
    staging:
      +materialized: view
      +docs:
        node_color: "lightblue"
    
    # Intermediate models - business logic transformations  
    intermediate:
      +materialized: view
      +docs:
        node_color: "orange"
    
    # Marts models - final tables for reporting
    marts:
      +materialized: table
      +docs:
        node_color: "green"

# Global configurations
vars:
  # Define start date for incremental models (if needed later)
  start_date: '2019-01-01'
  
  # Custom variables for business logic
  high_value_customer_threshold: 500
  vip_customer_orders: 10
  active_customer_days: 30

# Documentation
docs-paths: ["docs"]

# Snapshots configuration (for SCD if needed later)
snapshots:
  thelook_analytics:
    +target_schema: snapshots
    +strategy: timestamp
    +updated_at: updated_at