version: 2

sources:
  - name: dbt_looker_ecommerce
    description: "TheLook E-commerce dataset from BigQuery public data"
    tables:
      - name: users
        description: "Customer information and demographics"
        columns:
          - name: id
            description: "Unique user identifier"
            tests:
              - unique
              - not_null
          - name: email
            description: "User email address"
            tests:
              - not_null
          - name: created_at
            description: "User registration timestamp"
            tests:
              - not_null

      - name: orders
        description: "Order header information"
        columns:
          - name: order_id
            description: "Unique order identifier"
            tests:
              - unique
              - not_null
          - name: user_id
            description: "Customer who placed the order"
            tests:
              - not_null
              - relationships:
                  to: source('thelook_ecommerce', 'users')
                  field: id

      - name: order_items
        description: "Individual items within orders"
        columns:
          - name: id
            description: "Unique order item identifier"
            tests:
              - unique
              - not_null
          - name: order_id
            description: "Reference to parent order"
            tests:
              - not_null
          - name: product_id
            description: "Product purchased"
            tests:
              - not_null
          - name: sale_price
            description: "Price paid for this item"
            tests:
              - not_null

      - name: products
        description: "Product catalog information"
        columns:
          - name: id
            description: "Unique product identifier"
            tests:
              - unique
              - not_null
          - name: cost
            description: "Product cost to company"
            tests:
              - not_null
          - name: retail_price
            description: "Standard retail price"
            tests:
              - not_null

models:
  - name: stg_users
    description: "Cleaned and standardized user data"
    columns:
      - name: user_id
        description: "Unique user identifier"
        tests:
          - unique
          - not_null
      - name: email_clean
        description: "Cleaned email address (lowercase, trimmed)"
      - name: gender_clean
        description: "Standardized gender values"
      - name: age_group
        description: "Age grouped into buckets"

  - name: stg_orders
    description: "Cleaned and enriched order data"
    columns:
      - name: order_id
        description: "Unique order identifier"
        tests:
          - unique
          - not_null
      - name: status_clean
        description: "Standardized order status"
      - name: days_to_ship
        description: "Days between order creation and shipping"

  - name: stg_order_items
    description: "Cleaned order items with financial calculations"
    columns:
      - name: order_item_id
        description: "Unique order item identifier"
        tests:
          - unique
          - not_null
      - name: sale_price_clean
        description: "Cleaned sale price (rounded to 2 decimals)"
        tests:
          - not_null
      - name: price_tier
        description: "Categorized price level"

  - name: stg_products
    description: "Product data with profit calculations"
    columns:
      - name: product_id
        description: "Unique product identifier"
        tests:
          - unique
          - not_null
      - name: profit_margin
        description: "Profit margin in absolute terms"
      - name: profit_margin_pct
        description: "Profit margin as percentage"